'use client';

import type { PPTSvgElement } from '@/lib/types/slides';
import { useMemo } from 'react';

interface BaseSvgElementProps {
  readonly elementInfo: PPTSvgElement;
}

/**
 * Renders an inline SVG diagram generated by the LLM.
 *
 * Security notes:
 *  - The SVG was already sanitized server-side by Rust (stripped script/foreignObject tags).
 *  - We apply a belt-and-suspenders CSP via sandbox approach: the SVG is injected via
 *    dangerouslySetInnerHTML into an isolated div with pointer-events passthrough only.
 *  - No external images / fetch / eval can execute in an inline SVG on modern browsers
 *    when served from the same origin with a Content-Security-Policy that blocks unsafe-eval.
 */
export function BaseSvgElement({ elementInfo }: BaseSvgElementProps) {
  /**
   * Client-side additional sanitisation: strip any remaining on* event handlers
   * and javascript: URLs as an extra defensive layer.
   */
  const sanitized = useMemo(() => {
    if (!elementInfo.svg) return '';
    return elementInfo.svg
      // Remove inline event handlers like onload="...", onclick="...", etc.
      .replace(/\s+on\w+="[^"]*"/gi, '')
      .replace(/\s+on\w+='[^']*'/gi, '')
      // Remove javascript: URLs
      .replace(/javascript:[^"']*/gi, '');
  }, [elementInfo.svg]);

  if (!sanitized) {
    return (
      <div
        aria-label={elementInfo.alt ?? 'Diagram'}
        style={{
          width: '100%',
          height: '100%',
          display: 'flex',
          alignItems: 'center',
          justifyContent: 'center',
          background: '#f1f5f9',
          borderRadius: 8,
          color: '#64748b',
          fontSize: 12,
        }}
      >
        Diagram unavailable
      </div>
    );
  }

  return (
    <div
      aria-label={elementInfo.alt ?? 'Educational diagram'}
      role="img"
      style={{
        width: '100%',
        height: '100%',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        overflow: 'hidden',
      }}
      // SVG is sanitized server-side (Rust) + client-side (above regex).
      // This is safe for our educational use-case where SVGs come from our own LLM pipeline.
      // eslint-disable-next-line react/no-danger
      dangerouslySetInnerHTML={{ __html: sanitized }}
    />
  );
}
