-- Uniform tenant schema migration (superset columns, retry)
ALTER TABLE IF EXISTS audit_logs ADD COLUMN IF NOT EXISTS school_id UUID;
ALTER TABLE IF EXISTS audit_logs ADD COLUMN IF NOT EXISTS changes JSONB;

ALTER TABLE IF EXISTS fee_structures ADD COLUMN IF NOT EXISTS school_id UUID;
ALTER TABLE IF EXISTS fee_structures ADD COLUMN IF NOT EXISTS class_id UUID;
ALTER TABLE IF EXISTS fee_structures ADD COLUMN IF NOT EXISTS fee_type VARCHAR(50);
ALTER TABLE IF EXISTS fee_structures ADD COLUMN IF NOT EXISTS amount DECIMAL(10,2);
ALTER TABLE IF EXISTS fee_structures ADD COLUMN IF NOT EXISTS frequency VARCHAR(20);

ALTER TABLE IF EXISTS student_fees ADD COLUMN IF NOT EXISTS school_id UUID;
ALTER TABLE IF EXISTS student_fees ADD COLUMN IF NOT EXISTS fee_structure_id UUID;

ALTER TABLE IF EXISTS payments ADD COLUMN IF NOT EXISTS school_id UUID;
