use std::collections::HashMap;
pub fn get_snippet(id: &str) -> Option<&'static str> {
    match id {
        "action-types" => Some(include_str!("prompts/snippets/action-types.md")),
        "element-types" => Some(include_str!("prompts/snippets/element-types.md")),
        "image-instructions" => Some(include_str!("prompts/snippets/image-instructions.md")),
        "json-output-rules" => Some(include_str!("prompts/snippets/json-output-rules.md")),
        "media-safety-guidelines" => Some(include_str!("prompts/snippets/media-safety-guidelines.md")),
        "slide-generated-image-instructions" => Some(include_str!("prompts/snippets/slide-generated-image-instructions.md")),
        "slide-image-instructions" => Some(include_str!("prompts/snippets/slide-image-instructions.md")),
        "slide-video-instructions" => Some(include_str!("prompts/snippets/slide-video-instructions.md")),
        "speech-guidelines" => Some(include_str!("prompts/snippets/speech-guidelines.md")),
        "video-instructions" => Some(include_str!("prompts/snippets/video-instructions.md")),
        "whiteboard-reference" => Some(include_str!("prompts/snippets/whiteboard-reference.md")),
        _ => None,
    }
}
pub fn get_template(id: &str, file: &str) -> Option<&'static str> {
    match (id, file) {
        ("agent-system", "system.md") => Some(include_str!("prompts/templates/agent-system/system.md")),
        ("agent-system-wb-assistant", "system.md") => Some(include_str!("prompts/templates/agent-system-wb-assistant/system.md")),
        ("agent-system-wb-student", "system.md") => Some(include_str!("prompts/templates/agent-system-wb-student/system.md")),
        ("agent-system-wb-teacher", "system.md") => Some(include_str!("prompts/templates/agent-system-wb-teacher/system.md")),
        ("code-content", "system.md") => Some(include_str!("prompts/templates/code-content/system.md")),
        ("code-content", "user.md") => Some(include_str!("prompts/templates/code-content/user.md")),
        ("diagram-content", "system.md") => Some(include_str!("prompts/templates/diagram-content/system.md")),
        ("diagram-content", "user.md") => Some(include_str!("prompts/templates/diagram-content/user.md")),
        ("director", "system.md") => Some(include_str!("prompts/templates/director/system.md")),
        ("game-content", "system.md") => Some(include_str!("prompts/templates/game-content/system.md")),
        ("game-content", "user.md") => Some(include_str!("prompts/templates/game-content/user.md")),
        ("interactive-actions", "system.md") => Some(include_str!("prompts/templates/interactive-actions/system.md")),
        ("interactive-actions", "user.md") => Some(include_str!("prompts/templates/interactive-actions/user.md")),
        ("interactive-outlines", "system.md") => Some(include_str!("prompts/templates/interactive-outlines/system.md")),
        ("interactive-outlines", "user.md") => Some(include_str!("prompts/templates/interactive-outlines/user.md")),
        ("pbl-actions", "system.md") => Some(include_str!("prompts/templates/pbl-actions/system.md")),
        ("pbl-actions", "user.md") => Some(include_str!("prompts/templates/pbl-actions/user.md")),
        ("pbl-design", "system.md") => Some(include_str!("prompts/templates/pbl-design/system.md")),
        ("procedural-skill-content", "system.md") => Some(include_str!("prompts/templates/procedural-skill-content/system.md")),
        ("procedural-skill-content", "user.md") => Some(include_str!("prompts/templates/procedural-skill-content/user.md")),
        ("quiz-actions", "system.md") => Some(include_str!("prompts/templates/quiz-actions/system.md")),
        ("quiz-actions", "user.md") => Some(include_str!("prompts/templates/quiz-actions/user.md")),
        ("quiz-content", "system.md") => Some(include_str!("prompts/templates/quiz-content/system.md")),
        ("quiz-content", "user.md") => Some(include_str!("prompts/templates/quiz-content/user.md")),
        ("requirements-to-outlines", "system.md") => Some(include_str!("prompts/templates/requirements-to-outlines/system.md")),
        ("requirements-to-outlines", "user.md") => Some(include_str!("prompts/templates/requirements-to-outlines/user.md")),
        ("simulation-content", "system.md") => Some(include_str!("prompts/templates/simulation-content/system.md")),
        ("simulation-content", "user.md") => Some(include_str!("prompts/templates/simulation-content/user.md")),
        ("slide-actions", "system.md") => Some(include_str!("prompts/templates/slide-actions/system.md")),
        ("slide-actions", "user.md") => Some(include_str!("prompts/templates/slide-actions/user.md")),
        ("slide-content", "system.md") => Some(include_str!("prompts/templates/slide-content/system.md")),
        ("slide-content", "user.md") => Some(include_str!("prompts/templates/slide-content/user.md")),
        ("task-engine-outlines", "system.md") => Some(include_str!("prompts/templates/task-engine-outlines/system.md")),
        ("task-engine-outlines", "user.md") => Some(include_str!("prompts/templates/task-engine-outlines/user.md")),
        ("visualization3d-content", "system.md") => Some(include_str!("prompts/templates/visualization3d-content/system.md")),
        ("visualization3d-content", "user.md") => Some(include_str!("prompts/templates/visualization3d-content/user.md")),
        ("web-search-query-rewrite", "system.md") => Some(include_str!("prompts/templates/web-search-query-rewrite/system.md")),
        ("web-search-query-rewrite", "user.md") => Some(include_str!("prompts/templates/web-search-query-rewrite/user.md")),
        ("widget-teacher-actions", "system.md") => Some(include_str!("prompts/templates/widget-teacher-actions/system.md")),
        ("widget-teacher-actions", "user.md") => Some(include_str!("prompts/templates/widget-teacher-actions/user.md")),
        _ => None,
    }
}